### ISSUE TITLE
Неправильно строиться File Map

### ISSUE THREAD

**Issue by Graf009** [smelukov/webpack-runtime-analyzer#14]
http://prntscr.com/f0km6f

ОС: Windows 10
Может есть какие-то настройки?
Использую так:
`new RuntimeAnalyzerPlugin({
  mode: 'standalone',
  port: 0,
  open: true,
  watchModeOnly: false
})`

**Comment by smelukov** [comment]
Спасибо за issue, перепроверку обработку путей на Windows
