### ISSUE TITLE
Add possibility to activate the plugin not only in watch-mode

### ISSUE THREAD

**Issue by Tom910** [smelukov/webpack-runtime-analyzer#8]
Не происходит коннект к rempl серверам. В Webpack 2.0 по всей видимости выпилили раннер compiler.plugin('watch-run') и код в этом блоке никогда не выполнится. Но, даже если удалить этот враппер, то происходит коннект к rempl серверам но данные не передаются. Происходи
```
  socket  client connected Z01cOH0RQk2neGKIAAAA
  socket  client disconnected Z01cOH0RQk2neGKIAAAA
  socket  client connected 1qRHyc6S8151hcQnAAAB
```
на 91% происходит дисконект. И в итоге в rempl не попадают данные

**Comment by smelukov** [comment]
Нет, `watch-run` на месте - https://github.com/webpack/webpack/blob/479a0a4b7b22ed9c65c2f3c472a1be56db5ee0f0/lib/Compiler.js#L43
Плагин в 90% случаев тестировался именно на webpack 2 и rempl-cli 1.0.4
А какая у вас версия rempl-cli ?

**Comment by Tom910** [comment]
Версия - 1.0.6. 1.0.4 уже не получится поставить нормально, так как там изменили пути в под зависимостях и стоят ^

Но понял в чем проблема, watch-run это только для дев режима с отслеживанием изменений файлов. А если запускать в прод режиме, эта команда не выполнится. Мне кажется. стоит добавить режим, что бы работал плагин и для прод режима со всеми оптимизациями. Так как разделение на чанки и оптимизации именно тогда выполняются

**Comment by smelukov** [comment]
Да, плагин активизируется только в watch-режиме.
Это связано с тем, что задача обычно режима (не watch) - просто скомпилировать бандл и завершить процесс.
Если активировать плагин в обычном режиме, то процесс сборки  будет висеть бесконечно, пока его не убьешь вручную (например через `ctrl+c`).
Возможно стоит добавить параметр в настройки... что-то типа `onlyWatchMode`

**Comment by smelukov** [comment]
Кстати, rempl-cli был только что обновлен до 1.0.7
Попробуйте

**Comment by Tom910** [comment]
> Возможно стоит добавить параметр в настройки плагина... что-то типа onlyWatchMode: Boolean

Да, наверное лучше так сделать. webpack-bundle-analyzer тоже не дает завершиться сборки

**Comment by smelukov** [comment]
Сделаем ;)

**Comment by smelukov** [comment]
Опция `onlyWatchMode` добавлена в релиз 1.0.1
По умолчанию `onlyWatchMode=true`
